version: '3.4'

services:
  lighttpd:
    build: .
    restart: "unless-stopped"
    ports:
      - "8001:80"
    volumes:
      - ./htdocs:/var/www/localhost/htdocs/
      #- <config-directory>:/etc/lighttpd

